// <auto-generated />
using System;
using CompanyBlazor5.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyBlazor5.Server.Migrations
{
    [DbContext(typeof(CompanyBlazorDbContext))]
    partial class CompanyBlazorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyBlazor.Shared.Models.Department", b =>
                {
                    b.Property<int>("departmentNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departmentNo"));

                    b.Property<string>("departmentLocation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("departmentNo");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            departmentNo = 1,
                            departmentLocation = "London",
                            departmentName = "Development"
                        },
                        new
                        {
                            departmentNo = 2,
                            departmentLocation = "Zurich",
                            departmentName = "Development"
                        },
                        new
                        {
                            departmentNo = 3,
                            departmentLocation = "Osijek",
                            departmentName = "Development"
                        },
                        new
                        {
                            departmentNo = 4,
                            departmentLocation = "London",
                            departmentName = "Sales"
                        },
                        new
                        {
                            departmentNo = 5,
                            departmentLocation = "Zurich",
                            departmentName = "Sales"
                        },
                        new
                        {
                            departmentNo = 6,
                            departmentLocation = "Osijek",
                            departmentName = "Sales"
                        },
                        new
                        {
                            departmentNo = 7,
                            departmentLocation = "Basel",
                            departmentName = "Sales"
                        },
                        new
                        {
                            departmentNo = 8,
                            departmentLocation = "Lugano",
                            departmentName = "Sales"
                        });
                });

            modelBuilder.Entity("CompanyBlazor.Shared.Models.Employee", b =>
                {
                    b.Property<int>("employeeNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeNo"));

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int>("departmentNo")
                        .HasColumnType("int");

                    b.Property<int?>("departmentNo1")
                        .HasColumnType("int");

                    b.Property<string>("employeeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("lastModifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("employeeNo");

                    b.HasIndex("departmentNo1");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            employeeNo = 1,
                            Salary = 50000,
                            departmentNo = 4,
                            employeeName = "Fred Davies",
                            lastModifyDate = new DateTime(2023, 4, 10, 3, 11, 20, 681, DateTimeKind.Local).AddTicks(6272)
                        },
                        new
                        {
                            employeeNo = 2,
                            Salary = 50000,
                            departmentNo = 3,
                            employeeName = "Bernard Katic",
                            lastModifyDate = new DateTime(2023, 4, 10, 3, 11, 20, 681, DateTimeKind.Local).AddTicks(6272)
                        },
                        new
                        {
                            employeeNo = 3,
                            Salary = 30000,
                            departmentNo = 5,
                            employeeName = "Rich Davies",
                            lastModifyDate = new DateTime(2023, 4, 10, 3, 11, 20, 681, DateTimeKind.Local).AddTicks(6272)
                        },
                        new
                        {
                            employeeNo = 4,
                            Salary = 30000,
                            departmentNo = 6,
                            employeeName = "Eva Dobos",
                            lastModifyDate = new DateTime(2023, 4, 10, 3, 11, 20, 681, DateTimeKind.Local).AddTicks(6272)
                        },
                        new
                        {
                            employeeNo = 5,
                            Salary = 25000,
                            departmentNo = 8,
                            employeeName = "Mario Hunjadi",
                            lastModifyDate = new DateTime(2023, 4, 10, 3, 11, 20, 681, DateTimeKind.Local).AddTicks(6272)
                        },
                        new
                        {
                            employeeNo = 6,
                            Salary = 25000,
                            departmentNo = 7,
                            employeeName = "Jean Michele",
                            lastModifyDate = new DateTime(2023, 4, 10, 3, 11, 20, 681, DateTimeKind.Local).AddTicks(6272)
                        },
                        new
                        {
                            employeeNo = 7,
                            Salary = 25000,
                            departmentNo = 1,
                            employeeName = "Bill Gates",
                            lastModifyDate = new DateTime(2023, 4, 10, 3, 11, 20, 681, DateTimeKind.Local).AddTicks(6272)
                        },
                        new
                        {
                            employeeNo = 8,
                            Salary = 30000,
                            departmentNo = 3,
                            employeeName = "Maja Janic",
                            lastModifyDate = new DateTime(2023, 4, 10, 3, 11, 20, 681, DateTimeKind.Local).AddTicks(6272)
                        },
                        new
                        {
                            employeeNo = 9,
                            Salary = 35000,
                            departmentNo = 3,
                            employeeName = "Igor Horvat",
                            lastModifyDate = new DateTime(2023, 4, 10, 3, 11, 20, 681, DateTimeKind.Local).AddTicks(6272)
                        });
                });

            modelBuilder.Entity("CompanyBlazor.Shared.Models.Login", b =>
                {
                    b.Property<int>("loginNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("loginNo"));

                    b.Property<string>("loginPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("loginUserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("loginNo");

                    b.ToTable("Logins", (string)null);

                    b.HasData(
                        new
                        {
                            loginNo = 1,
                            loginPassword = new Encryption.Encrypt().Hash("ItsNotSoft"),
                            loginUserName = "Bill"
                        },
                        new
                        {
                            loginNo = 2,
                            loginPassword = new Encryption.Encrypt().Hash("trollsRule"),
                            loginUserName = "Jean"
                        });
                });

            modelBuilder.Entity("CompanyBlazor.Shared.Models.Employee", b =>
                {
                    b.HasOne("CompanyBlazor.Shared.Models.Department", "department")
                        .WithMany()
                        .HasForeignKey("departmentNo1");

                    b.Navigation("department");
                });
#pragma warning restore 612, 618
        }
    }
}
